<?php

/**
 * Implementation of hook_perm().
 */
function ih_acl_init() {
  $p = menu_get_item();
  $ips = variable_get('ih_acl_ips', array('127.0.0.1'));
  $paths = variable_get('ih_acl_paths', array('/^admin/i'));
  foreach($paths as $path) {
    if(preg_match($path, $p['path']) && !in_array($_SERVER['REMOTE_ADDR'],$ips)) {
      header('HTTP/1.1 500 Internal Server Error');
      echo "error no. 2 !";
      die();
    }
  }
}
